version: '3.8'

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    volumes:
      - ../.db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: archc_database
      TZ: America/Sao_Paulo