version: '3.8'

services:
  database:
    image: postgres:alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - ../.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: passin
      TZ: GMT+3
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080