version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ../.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: archc_database
      TZ: GMT+3