version: '3.8'

services:
  database:
    image: mysql
    container_name: database
    restart: always
    volumes:
      - ../.db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      TZ: America/Sao_Paulo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080